### ISSUE TITLE
research: considerations

### ISSUE THREAD

**Issue by karasakalmt** [SphinxDB/Sphinx-Verifier-OnChain#1]
Find papers and resources about how can we optimize the verification process and make consideration suggestions

**Comment by codekaya** [comment]
https://vitalik.ca/general/2021/06/18/verkle.html
https://hackmd.io/@liamzebedee/H1ejQCoHj
https://intelchen.medium.com/understanding-zero-knowledge-proofs-in-15-mins-through-snark-and-stark-7638311f0cc9
